Task : cls
Experiment : AttnBaseline-Performance-reproduce
seed : 42
data: 
    train: /ml_data/retrieval_data/train_preprocess2.json
    valid : /ml_data/retrieval_data/valid_preprocess2.json
    test: /ml_data/retrieval_data/test_preprocess2.json
    context : /home/jisukim/DPR/db/datasets/context_total.parquet
    bm_25: False     
    spath: gold32
    num: 2
hyper_params: 
    tokenizer_max_length : 512
    batch_size : 653
model:
    text_model_path : klue/roberta-base      # one of BertPretrainedModel 
    device: cuda:1
    question_model_path: /home/jisukim/DPR/dpr_model/results/question_gold_32.pt
    passage_model_path: /home/jisukim/DPR/dpr_model/results/passage_gold_32.pt
faiss:
    fname: /home/jisukim/DPR/db/faiss_index/total_index_batch_32.index
    path: /home/jisukim/DPR/db/faiss_index/total_index_batch_32.index