Task : cls
seed : 42
data: 
    train: /ml_data/retrieval_data/train_preprocess2.json
    valid : /ml_data/retrieval_data/valid_preprocess2.json
    test: /ml_data/retrieval_data/test_preprocess2.json
    context : /ml_data/retrieval_data/context.json
    bm_25: False    
    inference: True 
    dtype: test   
    num: 1
    spath: gold_32
hyper_params : 
    tokenizer_max_length : 512
    batch_size : 32
model:
    text_model_path : klue/roberta-base      # one of BertPretrainedModel 
    device: cuda:1
    passage_model_path: /home/jisukim/DPR/dpr_model/results/passage_gold_32.pt
faiss:
    path: /home/jisukim/DPR/db/faiss_index/total_index_batch_32.index
    context: /home/jisukim/DPR/db/datasets/context_total.parquet